import crypto from "crypto";
const rateState=new Map(),WINDOW=60000,LIMIT=10;
function ip(req){return String(req.headers["x-forwarded-for"]||"unknown").split(",")[0].trim();}
function cors(req,res){const o=req.headers.origin||"";if(["https://dynexal.com","https://www.dynexal.com"].includes(o)||(process.env.VERCEL_URL&&o==="https://"+process.env.VERCEL_URL))res.setHeader("Access-Control-Allow-Origin",o);res.setHeader("Vary","Origin");res.setHeader("Access-Control-Allow-Methods","POST,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type");}
function limit(req,res){const now=Date.now(),k=ip(req),e=rateState.get(k);if(!e||now-e.t>=WINDOW){rateState.set(k,{t:now,n:1});return true}e.n++;if(e.n>LIMIT){res.setHeader("Retry-After","60");return false}return true}
async function db(path,init={}){const r=await fetch(process.env.SUPABASE_URL+"/rest/v1/"+path,{...init,headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:"Bearer "+process.env.SUPABASE_SERVICE_ROLE_KEY,"Content-Type":"application/json",Prefer:"return=representation",...(init.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?[]:r.json()}
function certNo(){const y=new Date().getUTCFullYear();return "DYN-BCFD-"+y+"-"+crypto.randomBytes(3).toString("hex").toUpperCase()}
export default async function handler(req,res){cors(req,res);if(req.method==="OPTIONS")return res.status(204).end();if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});if(!limit(req,res))return res.status(429).json({error:"Too many submission requests. Try again later."});try{const body=typeof req.body==="string"?JSON.parse(req.body||"{}"):(req.body||{}),attemptId=String(body.attemptId||""),answers=Array.isArray(body.answers)?body.answers:[];if(!/^[0-9a-f-]{36}$/i.test(attemptId)||answers.length===0)return res.status(400).json({error:"Invalid exam submission."});const attempts=await db("exam_attempts?id=eq."+encodeURIComponent(attemptId)+"&select=id,certification_id,candidate_name,candidate_email,question_ids,started_at,expires_at,status,score_percentage,passed&limit=1");const attempt=attempts[0];if(!attempt)return res.status(404).json({error:"Exam attempt not found."});if(attempt.status!=="started")return res.status(409).json({error:"This exam has already been submitted."});const now=new Date();const expired=now.getTime()>new Date(attempt.expires_at).getTime();const ids=Array.isArray(attempt.question_ids)?attempt.question_ids:[];const questions=await db("certification_questions?id=in.("+ids.join(",")+")&active=eq.true&select=id,correct_option");const key=new Map(questions.map(q=>[q.id,q.correct_option]));const submitted=new Map();for(const a of answers){const id=String(a.questionId||"");if(ids.includes(id)&&!submitted.has(id))submitted.set(id,String(a.selectedOption||"").slice(0,10));}
let correct=0;const answerRows=[];for(const id of ids){const selected=submitted.get(id)||null;const isCorrect=!expired&&selected!==null&&selected===key.get(id);if(isCorrect)correct++;answerRows.push({attempt_id:attempt.id,question_id:id,selected_option:selected,is_correct:isCorrect})}
const certs=await db("certifications?id=eq."+attempt.certification_id+"&select=id,name,passing_percentage&limit=1");const cert=certs[0];if(!cert)return res.status(500).json({error:"Certification configuration not found."});const score=Number(((correct/ids.length)*100).toFixed(2));const passed=!expired&&score>=Number(cert.passing_percentage);const updated=await db("exam_attempts?id=eq."+encodeURIComponent(attempt.id)+"&status=eq.started",{method:"PATCH",body:JSON.stringify({submitted_at:now.toISOString(),score_percentage:score,passed,status:"submitted"})});if(!updated.length)return res.status(409).json({error:"This exam was submitted by another request."});await db("exam_answers",{method:"POST",body:JSON.stringify(answerRows)});let certificate=null;if(passed){const number=certNo();const hash=crypto.createHash("sha256").update(number+"|"+attempt.id+"|"+attempt.candidate_email).digest("hex");const rows=await db("certificates",{method:"POST",body:JSON.stringify({attempt_id:attempt.id,certificate_number:number,candidate_name:attempt.candidate_name,certification_name:cert.name,issued_at:now.toISOString(),status:"VALID",verification_hash:hash})});certificate={certificateNumber:rows[0].certificate_number,issuedAt:rows[0].issued_at,verificationUrl:"https://dynexal.com/verify.html?id="+encodeURIComponent(rows[0].certificate_number)}}return res.status(200).json({submitted:true,expired,scorePercentage:score,correctAnswers:correct,totalQuestions:ids.length,passingPercentage:Number(cert.passing_percentage),passed,certificate})}catch(e){console.error("exam-submit",e);return res.status(500).json({error:"Unable to submit exam"})}}